GET http://localhost:5277/books

###

GET http://localhost:5277/

###

GET http://localhost:5277/books/1

###

POST http://localhost:5277/books
Content-Type: application/json

  {
    "Title": "Words of Radience", 
    "Author": "Brandon Sanderson", 
    "Genre": "Epic Fantasy", 
    "ISBN": "735-2-465-19252-2", 
    "Condition": "Good", 
    "Description": "Book 2 of the Stormlight Archives",
    "Length": 1220
  }

###

PUT http://localhost:5277/books/3
Content-Type: application/json

  {
    "title": "Without Remorse",
    "author": "Tom Clancy",
    "genre": "Mility Thriller",
    "isbn": "970-0-425-14332-2",
    "condition": "New",
    "description": "Military/Spy thriller. Action",
    "length": 780
  }

### 

DELETE http://localhost:5277/books/1