GET http://localhost:5277/books

###

GET http://localhost:5277/

###

GET http://localhost:5277/books/3

###

POST http://localhost:5277/books
Content-Type: application/json

  {
    "title": "Words of Radience", 
    "author": "Brandon Sanderson", 
    "genreId": 1, 
    "ISBN": "735-2-465-19252-2", 
    "conditionId": 3, 
    "description": "Book 2 of the Stormlight Archives",
    "length": 1220
  }

###

PUT http://localhost:5277/books/3
Content-Type: application/json

  {
    "title": "Without Remorse",
    "author": "Tom Clancy",
    "genreId": 4,
    "isbn": "970-0-425-14332-2",
    "conditionId": 1,
    "description": "Military/Spy thriller. Action",
    "length": 780
  }

### 

DELETE http://localhost:5277/books/1